// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3932.RobotTest;
    
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {

    public static CANTalon mecanumDriveRightBack;
    public static CANTalon mecanumDriveRightFront;
    public static CANTalon mecanumDriveLeftBack;
    public static CANTalon mecanumDriveLeftFront;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static RobotDrive mecanumDriveRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {

        mecanumDriveRightBack = new CANTalon(5);
        
        
        mecanumDriveRightFront = new CANTalon(4);
        
        
        mecanumDriveLeftBack = new CANTalon(3);
        
        
        mecanumDriveLeftFront = new CANTalon(2);
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        mecanumDriveRobotDrive41 = new RobotDrive(mecanumDriveLeftFront, mecanumDriveLeftBack,
              mecanumDriveRightFront, mecanumDriveRightBack);
        
        mecanumDriveRobotDrive41.setSafetyEnabled(true);
        mecanumDriveRobotDrive41.setExpiration(0.1);
        mecanumDriveRobotDrive41.setSensitivity(0.5);
        mecanumDriveRobotDrive41.setMaxOutput(1.0);

        mecanumDriveRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        mecanumDriveRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
