// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3932.RobotTest.subsystems;

import org.usfirst.frc3932.RobotTest.RobotMap;
import org.usfirst.frc3932.RobotTest.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;

import java.lang.Math;

/**
 *
 */
public class MecanumDrive extends Subsystem {
    CANTalon leftFront = RobotMap.mecanumDriveLeftFront;
    CANTalon leftBack = RobotMap.mecanumDriveLeftBack;
    CANTalon rightFront = RobotMap.mecanumDriveRightFront;
    CANTalon rightBack = RobotMap.mecanumDriveRightBack;
    
    
    
    RobotDrive drive = RobotMap.mecanumDriveRobotDrive41;

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void drive(double x, double y, double rotation){
    	drive.mecanumDrive_Cartesian(adjust(x), adjust(y), adjust(rotation), 0);
    }
    
    private double adjust(double val){
    	return adjust(val, 1000);
    }
    
    private double adjust(double val, double factor){
    	return (Math.pow(factor, val) - 1) / (factor-1);
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

